# https://github.com/marketplace/actions/lighthouse-ci-action
name: Lighthouse Audit
on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rlespinasse/github-slug-action@v1.1.x
      - name: Run Lighthouse and test budgets
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://bus2.dabase.com/
          temporaryPublicStorage: true
