# https://github.com/marketplace/actions/lighthouse-ci-action
name: Lighthouse Audit
on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
        with:
          urls: |
            https://bus2.dabase.com
            https://bus2.dabase.com/?id=83059
          budgetPath: ./budget.json # test performance budgets
          temporaryPublicStorage: true
          uploadArtifacts: true
