# https://github.com/marketplace/actions/lighthouse-ci-action
name: Lighthouse Audit
on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Audit live URL
        uses: jakejarvis/lighthouse-action@master
        with:
          url: 'https://bus2.dabase.com/'
      - name: Upload results as an artifact
        uses: actions/upload-artifact@master
        with:
          name: report
          path: './report'
